name: release

on:
  push:
    branches:
      - 'main'

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: test step
        run: |
          ls -la
          pwd
          whoami
        
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: $GITHUB_SHA
          tag_name: ${{ github.ref }}
          body_path: README.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
          
      - name: upload test artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./README.md
          asset_name: test.tar.gz
          asset_content_type: application/gzip
      

